name: "Agrgar grupo"

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'bot|')
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Setup Python Modules
      run: pip3 install requests beautifulsoup4 validators
    
    - name: Add link to file
      env:
        ISSUE_TITLE: ${{ github.event.issue.title }}
      run: |
        CLAVE=$(echo $ISSUE_TITLE | cut -d "|" -f2)
        NRC=$(echo $ISSUE_TITLE | cut -d "|" -f3)
        LINK=$(echo $ISSUE_TITLE | cut -d "|" -f4)
        python3 tools/add_link.py $CLAVE $NRC $LINK
    
    - name: Commit changes
        run: |
          git config --global user.name 'Lord Friky'
          git config --global user.email 'lordfriky@users.noreply.github.com'
          git add --all
          git commit -am ":robot: Grupo añadido automáticamente"
          git push