name: "Añadir grupo"

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.title == '[BOT] Añadir enlace de invitación' }}

    env:
      ISSUE_BODY: ${{ github.event.issue.body }}
      GIT_USER: ${{ github.repository_owner }}
      GITHUB_TOKEN: ${{ github.token }}

    steps:
    - name: Installing environment tools
      run: sudo snap install --classic hub

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Setup Python Modules
      run: pip3 install requests beautifulsoup4 html5lib

    - name: Add link to file
      run: |
        python3 tools/add_link.py

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@users.noreply.github.com'
        git add --all
        git commit -am ":robot: Grupo añadido automáticamente"
        git push

    - name: Close issue
      run: |
        hub api -XPATCH repos/${{ github.repository }}/issues/${{ github.event.issue.number }} -f state=closed
